/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveSubscriptionCard: typeof import('./src/components/dashboard/ActiveSubscriptionCard.vue')['default']
    ClashModeCard: typeof import('./src/components/dashboard/ClashModeCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EnhancedTrafficStats: typeof import('./src/components/dashboard/EnhancedTrafficStats.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    MergedConfigDialog: typeof import('./src/components/MergedConfigDialog.vue')['default']
    ModeSwitcher: typeof import('./src/components/proxy/ModeSwitcher.vue')['default']
    ProxyGrid: typeof import('./src/components/proxy/ProxyGrid.vue')['default']
    ProxyGroup: typeof import('./src/components/proxy/ProxyGroup.vue')['default']
    ProxyGroupNavigator: typeof import('./src/components/proxy/ProxyGroupNavigator.vue')['default']
    ProxyHead: typeof import('./src/components/proxy/ProxyHead.vue')['default']
    ProxyItem: typeof import('./src/components/proxy/ProxyItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleEditorDialog: typeof import('./src/components/RuleEditorDialog.vue')['default']
    RuntimeInfoCard: typeof import('./src/components/dashboard/RuntimeInfoCard.vue')['default']
    ScriptEditorDialog: typeof import('./src/components/ScriptEditorDialog.vue')['default']
    SidebarTraffic: typeof import('./src/components/Layout/SidebarTraffic.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    SubscriptionCard: typeof import('./src/components/SubscriptionCard.vue')['default']
    SubscriptionEditDialog: typeof import('./src/components/SubscriptionEditDialog.vue')['default']
    TrafficGraph: typeof import('./src/components/dashboard/TrafficGraph.vue')['default']
    TrafficIndicator: typeof import('./src/components/dashboard/TrafficIndicator.vue')['default']
    TrafficInfo: typeof import('./src/components/TrafficInfo.vue')['default']
    TrafficStats: typeof import('./src/components/dashboard/TrafficStats.vue')['default']
  }
}
